# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MazeSolve.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MazeSolveWindow(object):
    def setupUi(self, MazeSolveWindow):
        MazeSolveWindow.setObjectName("MazeSolveWindow")
        MazeSolveWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MazeSolveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PyGameMazeWidget = QtWidgets.QWidget(self.centralwidget)
        self.PyGameMazeWidget.setGeometry(QtCore.QRect(0, 0, 561, 571))
        self.PyGameMazeWidget.setObjectName("PyGameMazeWidget")
        self.InstructionsWidget = QtWidgets.QWidget(self.centralwidget)
        self.InstructionsWidget.setGeometry(QtCore.QRect(559, -1, 231, 571))
        self.InstructionsWidget.setObjectName("InstructionsWidget")
        self.label = QtWidgets.QLabel(self.InstructionsWidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.InstructionsWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 131, 51))
        self.label_2.setObjectName("label_2")
        MazeSolveWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MazeSolveWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MazeSolveWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MazeSolveWindow)
        self.statusbar.setObjectName("statusbar")
        MazeSolveWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MazeSolveWindow)
        QtCore.QMetaObject.connectSlotsByName(MazeSolveWindow)

    def retranslateUi(self, MazeSolveWindow):
        _translate = QtCore.QCoreApplication.translate
        MazeSolveWindow.setWindowTitle(_translate("MazeSolveWindow", "MainWindow"))
        self.label.setText(_translate("MazeSolveWindow", "Instructions"))
        self.label_2.setText(_translate("MazeSolveWindow", "1. Example Instruction"))
        self.menuHelp.setTitle(_translate("MazeSolveWindow", "Help"))
        self.menuExit.setTitle(_translate("MazeSolveWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MazeSolveWindow = QtWidgets.QMainWindow()
    ui = Ui_MazeSolveWindow()
    ui.setupUi(MazeSolveWindow)
    MazeSolveWindow.show()
    sys.exit(app.exec_())
